openapi: 3.0.0
info:
  title: Open Weather Map API
  version: '1.0'
  contact:
    name: Support
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: coord
                type: object
                properties:
                  cod:
                    type: number
                  lon:
                    type: number
                    description: Longitude
                  name:
                    type: number
                    description: City Name
                  lat:
                    type: string
                    description: Latitude
                  id:
                    type: number
                    description: Your unique API key
                  sys:
                    type: object
                  type:
                    type: number
                    description: Type of wind
                  country:
                    type: string
                    description: Country code
                  sunrise:
                    type: number
                    description: Sunrise time
                  sunset:
                    type: number
                    description: Sunset time
                  clouds:
                    type: object
                    description: Clouds
                    properties:
                      all:
                        type: string
                        description: Cloudiness %
                      wind:
                        type: object
                        description: Wind
                        properties:
                          speed:
                            type: number
                            description: Wind speed
                          deg:
                            type: number
                            description: degrees
                          visibility:
                            type: number
                            description: Visibility
                          main:
                            type: object
                            description: Main
                            properties:
                              temp:
                                type: number
                                description: Temperature
                              feels_like:
                                type: number
                                description: Feels like
                              temp_min:
                                type: number
                                description: Minimum temperature
                              temp_max:
                                type: number
                                description: Maximum temperature
                              pressure:
                                type: number
                                description: Pressure
                              humidity:
                                type: number
                                description: Humidity
                              base:
                                type: string
                              weather:
                                type: array
                                description: Weather
                                items:
                                  type: object
                                  properties:
                                    id:
                                      type: number
                                      description: Your unique API key
                                    main:
                                      type: string
                                    description:
                                      type: string
                                      description: Description
                                    icon:
                                      type: string
                                      description: Icon
              examples: {}
            application/xml:
              schema:
                type: object
                properties: {}
            multipart/form-data:
              schema:
                type: object
                properties:
                  '':
                    type: string
            text/html:
              schema:
                type: object
                properties:
                  '':
                    type: string
      operationId: get-weather
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**Zip code*. Search by zip code. Example 950950.'
        - schema:
            type: string
          in: query
          name: units
          description: 'Units of measurement. Possible values: standard, metric and imperial.'
        - schema:
            type: string
          in: query
          name: q
          description: 'City name, state code and country code divided by comma, use ISO 3166 country codes.'
        - schema:
            type: string
          in: query
          name: id
          description: Your unique API key
        - schema:
            type: string
          in: query
          name: lat
          description: Latitude. Example 35.
        - schema:
            type: string
          in: query
          name: lon
          description: Longitude. Example 139.
        - schema:
            type: string
          in: query
          name: lang
          description: Language. Example **en""
        - schema:
            type: string
          in: query
          name: mode
          description: Response format. Possible values are xml and html.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
        description: ''
      description: |-
        Get the current weather, daily forecast for 16 days, and a three-hour interval forecast for 5 days for your city.Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your station location stations. Data is available in JSON, XML, or HTML format. **Note** This sample Swagger file covers the 'current' endpoint only from the OpenWeatherMap API. <br/><br/>
        **Note** All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the 'id' parameter) will provide the most precise location results.
    parameters: []
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: API Key
      type: apiKey
      in: query
