openapi: 3.0.0
info:
  title: Open Weather Map API
  version: '1.0'
  contact:
    name: Support
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
  description: 'Get the current weather, daily forecast for 16 days, and a three-hour-interval forecast for 5 days for your city. Helpful stats, graphics, and this day in history charts are available for your reference. Interactive maps show precipitation, clouds, pressure, wind around your location stations. Data is available in JSON, XML, or HTML format. **Note**: This sample Swagger file covers the `current` endpoint only from the OpenWeatherMap API. <br/><br/> **Note**: All parameters are optional, but you must select at least one parameter. Calling the API by city ID (using the `id` parameter) will provide the most precise location results.'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
    description: prod
paths:
  /weather:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-weather
      security:
        - app_id: []
      parameters:
        - schema:
            type: string
          in: query
          name: zip
        - schema:
            type: string
          in: query
          name: units
        - schema:
            type: string
          in: query
          name: q
        - schema:
            type: string
          in: query
          name: id
        - schema:
            type: string
          in: query
          name: lat
        - schema:
            type: string
          in: query
          name: lon
        - schema:
            type: string
          in: query
          name: lang
        - schema:
            type: string
          in: query
          name: mode
    parameters: []
components:
  schemas: {}
  securitySchemes:
    app_id:
      name: API Key
      type: apiKey
      in: query
